name: github actions + heroku

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: set Procfile
        run: cp Proc/procfile-real Procfile

      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.heroku_api_key }}
          heroku_email: ${{ secrets.heroku_email }}
          heroku_app_name: ${{ secrets.heroku_app_name }}
